packages:
  - './packages/*'
  - './srcbook'

catalog:
  zod: '^3.25.76'
  marked: '^14.1.2'
  ws: '^8.17.0'
  ai: '^6.0.149'
  '@ai-sdk/anthropic': '^3.0.67'
  '@ai-sdk/google': '^3.0.59'
  '@ai-sdk/openai': '^3.0.51'
  '@ai-sdk/provider': '^3.0.8'
