packages:
  - './packages/*'
  - './srcbook'

catalog:
  zod: '^3.23.8'
  marked: '^12.0.2'
  prettier: '^3.3.1'
  typescript: '^5.4.5'
  '@types/node': '^20.14.2'
  ws: '^8.17.0'
  '@ai-sdk/openai': '^0.0.34'
  '@ai-sdk/anthropic': '^0.0.37'
