#!/bin/bash

set -e

echo 'Building srcbook by compiling the shared, web, and api packages to the srcbook/dist/ directory.'
echo 'Building shared...'
pnpm --filter shared build

echo 'Building client...'
pnpm --filter web build

echo 'Moving client files to srcbook/web_dist/...'
rm -rf srcbook/web_dist/
mkdir -p srcbook/web_dist/
cp -R packages/web/dist/* srcbook/web_dist

echo 'Building api...'
cd packages/api/
pnpm build

echo 'Packing api...'
pnpm pack --pack-destination ../../srcbook/

echo 'Vendorizing api into srcbook...'
cd ../../srcbook/
TARBALL_NAME=$(ls srcbook-api-*.tgz)

rm -rf vendor/
mkdir vendor/

tar -xzf $TARBALL_NAME -C vendor/ --strip-components=1

rm $TARBALL_NAME
echo 'All done!'
